name: check.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --group build --group lint

      - name: Check
        run: |
          bash ./script/mypy.sh
